services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      extra_hosts:
        - "host.docker.internal:host-gateway"
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - NODE_ENV=production
      - PORT=3000
    env_file:
      - .env
    ports:
      - '127.0.0.1:8010:3000'
    logging:
      driver: 'json-file'
      options:
        max-size: '50m'
