FROM node:22-alpine

WORKDIR /opt/vaalimasiina

# Copy configuration files
COPY .eslint* package.json pnpm-lock.yaml ./

# Set environment variables
ENV NODE_ENV=development \
    HOSTNAME=0.0.0.0

# Install dependencies
RUN pnpm install
