services:
  app:
    image: ghcr.io/fyysikkokilta/fk-vaalimasiina:latest
    restart: always
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    env_file:
      - .env
    ports:
      - '127.0.0.1:8010:3000'
    logging:
      driver: 'json-file'
      options:
        max-size: '50m'
